<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-BackgroundService-E22449C8-9651-4778-A901-C4F3D2DD2566</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>BackgroundService</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.0.16" />
        <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.0.16" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
        <PackageReference Include="MySql.Data.EntityFrameworkCore" Version="8.0.22" />
        <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
        <PackageReference Include="SqlKata" Version="4.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
      <Content Include="..\Dockerfile">
        <Link>Dockerfile</Link>
      </Content>
    </ItemGroup>
</Project>